export const dummyStudents = [
	{ id: "1", fullname: "John Doe", course_Year: "BSIT 3rd Year" },
	{ id: "2", fullname: "Jane Smith", course_Year: "BSCS 2nd Year" },
	{ id: "3", fullname: "Michael Johnson", course_Year: "BSECE 4th Year" },
	{ id: "4", fullname: "Emily Davis", course_Year: "BSIT 1st Year" },
	{ id: "5", fullname: "William Brown", course_Year: "BSCS 3rd Year" },
	{ id: "6", fullname: "Olivia Wilson", course_Year: "BSIT 2nd Year" },
	{ id: "7", fullname: "James Taylor", course_Year: "BSEE 4th Year" },
	{ id: "8", fullname: "Sophia Anderson", course_Year: "BSIT 3rd Year" },
	{ id: "9", fullname: "Benjamin Martinez", course_Year: "BSIT 2nd Year" },
	{ id: "10", fullname: "Isabella Thomas", course_Year: "BSCS 1st Year" },
	{ id: "11", fullname: "Liam White", course_Year: "BSECE 3rd Year" },
	{ id: "12", fullname: "Charlotte Harris", course_Year: "BSIT 4th Year" },
	{ id: "13", fullname: "Ethan Clark", course_Year: "BSIT 2nd Year" },
	{ id: "14", fullname: "Amelia Lewis", course_Year: "BSCS 3rd Year" },
	{ id: "15", fullname: "Mason Walker", course_Year: "BSEE 1st Year" },
	{ id: "16", fullname: "Mia Hall", course_Year: "BSIT 2nd Year" },
	{ id: "17", fullname: "Lucas Allen", course_Year: "BSCS 4th Year" },
	{ id: "18", fullname: "Harper Young", course_Year: "BSIT 3rd Year" },
	{ id: "19", fullname: "Henry King", course_Year: "BSECE 2nd Year" },
	{ id: "20", fullname: "Evelyn Scott", course_Year: "BSIT 1st Year" },
];
